jobs:
- job: 'Win64'
  timeoutInMinutes: 90
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    LLVM_VERSION: 7.0.1
    CLANG_VERSION: 7.0.1
    HOST_LDC_VERSION: 1.13.0
    VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
    EXTRA_CMAKE_FLAGS: -DBUILD_LTO_LIBS=ON
    OS: win64
    MODEL: 64
    ARCH: x64
  steps:
    - template: .azure-pipelines/windows.yml

- job: 'Win32'
  timeoutInMinutes: 90
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    LLVM_VERSION: 7.0.1
    CLANG_VERSION: 7.0.1
    HOST_LDC_VERSION: 1.13.0
    VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
    EXTRA_CMAKE_FLAGS: -DBUILD_LTO_LIBS=ON
    OS: win32
    MODEL: 32
    ARCH: x86
    CFLAGS: -m32
    CXXFLAGS: -m32
    ASMFLAGS: -m32
  steps:
    - template: .azure-pipelines/windows.yml
